# Generated by Django 5.2.4 on 2025-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='text',
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usersubmission',
            name='submitted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
