# Generated by Django 5.2.4 on 2025-08-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubmission',
            name='won',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubmission',
            name='word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
