# Generated by Django 5.2.4 on 2025-08-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usersubmission_text_usersubmission_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubmission',
            name='name',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='score',
        ),
        migrations.RemoveField(
            model_name='usersubmission',
            name='submitted_at',
        ),
    ]
