# Generated by Django 5.2.4 on 2025-08-03 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usersubmission_won_usersubmission_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
